### ISSUE TITLE
I am getting an error "Unable to contact server".

### ISSUE THREAD

**Issue by spmanutd007** [infoxicator/angular2-soap#6]
I understand that this issue is because of "e" being null, but what can i do to make e not null?Can you help @infoxicator ? I am providing the code of soap.service.ts

`import { Injectable } from '@angular/core';
import SOAPClient from '../../soapclient.js';

@Injectable()
export class SoapService {

  public soapParams: any;
  public soapClient: any;

  constructor() { }

  post(url, action, params)
  {
    var soapCallback;
    console.log("entered post");
    this.soapParams = new SOAPClient.SOAPClientParameters;
    this.soapClient = SOAPClient.SOAPClient;
    return new Promise((resolve, reject) => {
      //Create SOAPClientParameters
      for (var param in params) {
        this.soapParams.add(param, params[param]);
      }
      //Create Callback
      console.log("callback");

       soapCallback= function(e, status) {
         
        if (e == null || e.constructor.toString().indexOf("function Error()") != -1) {
          alert("Unable to contact the server: " + status);
        } else {
          
          resolve(e);
        }

      }
      console.log("hello");
      this.soapClient.invoke(url, action, this.soapParams, true, soapCallback);
      console.log("hi");
    });
  }
  
  setCredentials(username, password) {
    console.log("hi1");
    this.soapClient.username = username;
    this.soapClient.password = password;
  }
}
`

**Comment by infoxicator** [comment]
Hi @spmanutd007 the soapclient.js passes null and a error message text when the xmlhttp request status is other than 200 ok. So if your server returns 500 for example you will get null on the call back because the request wasn't completed successfully, please check your request and the network tab on chrome dev tools to see what is the error you are getting

**Comment by spmanutd007** [comment]
Hi @infoxicator  , the server is returning a 404
![screenshot 28](https://user-images.githubusercontent.com/30754288/43448203-f4f4921c-94ca-11e8-853d-36577f18c381.png)
![screenshot 30](https://user-images.githubusercontent.com/30754288/43448301-3819f03c-94cb-11e8-98b2-57f4e3784b07.png)
the webservice used is the same you provided,what should be the response expected?

**Comment by infoxicator** [comment]
@spmanutd007 you need to point the url to the location of your webservices and make sure that adding ?wsdl shows the correct location of the wsdl for your webservice. This is not related to the library but to its use. thanks
